### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by x4080** [dranger003/llama.cpp-dotnet#3]
Hi, I tried to build for apple silicon, so I changed all x64 to arm64, the build is success and when I try to run, here's the result:
```
% ./LlamaCppCli
USAGE:
    LlamaCppCli.dll <SampleIndex> <ModelPath> [TemplatePath] [GpuLayers]
SAMPLES:
    [0] = RawInterfaceSample
    [1] = WrappedInterfaceSampleWithoutSession
    [2] = WrappedInterfaceSampleWithSession
    [3] = WrappedInterfaceSampleWithSessionInteractive
    [4] = GetEmbeddings
edwardnone@Edwards-Mac-mini Release % 
```
So the build is success, but when I put parameter :
```
 % ./LlamaCppCli 3 /Users/edwardnone/llama.cpp/models/Wizard-Vicuna-13B-Uncensored.ggml.q5_0.bin
```

this error occurs :
```
Running sample (WrappedInterfaceSampleWithSessionInteractive)...
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'llama' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama.dylib' (no such file)
dlopen(/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama.dylib, 0x0001): tried: '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama.dylib' (no such file), '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama.dylib' (no such file)
dlopen(llama.dylib, 0x0001): tried: 'llama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSllama.dylib' (no such file), '/usr/lib/llama.dylib' (no such file, not in dyld cache), 'llama.dylib' (no such file), '/usr/local/lib/llama.dylib' (no such file), '/usr/lib/llama.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama.dylib' (no such file)
dlopen(/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama.dylib, 0x0001): tried: '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama.dylib' (no such file), '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama.dylib' (no such file)
dlopen(libllama.dylib, 0x0001): tried: 'libllama.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibllama.dylib' (no such file), '/usr/lib/libllama.dylib' (no such file, not in dyld cache), 'libllama.dylib' (no such file), '/usr/local/lib/libllama.dylib' (no such file), '/usr/lib/libllama.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/llama' (no such file)
dlopen(/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama, 0x0001): tried: '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama' (no such file), '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/llama' (no such file)
dlopen(llama, 0x0001): tried: 'llama' (no such file), '/System/Volumes/Preboot/Cryptexes/OSllama' (no such file), '/usr/lib/llama' (no such file, not in dyld cache), 'llama' (no such file), '/usr/local/lib/llama' (no such file), '/usr/lib/llama' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libllama' (no such file)
dlopen(/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama, 0x0001): tried: '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama' (no such file), '/Users/edwardnone/llama.cpp-dotnet/arm64/Release/libllama' (no such file)
dlopen(libllama, 0x0001): tried: 'libllama' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibllama' (no such file), '/usr/lib/libllama' (no such file, not in dyld cache), 'libllama' (no such file), '/usr/local/lib/libllama' (no such file), '/usr/lib/libllama' (no such file, not in dyld cache)

   at LlamaCppLib.LlamaCppInterop.llama_context_default_params()
   at LlamaCppLib.LlamaCpp.Load(String modelPath, String loraPath, String loraBaseModelPath) in /Users/edwardnone/llama.cpp-dotnet/LlamaCppLib/LlamaCpp.cs:line 74
   at LlamaCppCli.Program.WrappedInterfaceSampleWithSessionInteractive(String[] args) in /Users/edwardnone/llama.cpp-dotnet/LlamaCppCli/Program.cs:line 428
   at LlamaCppCli.Program.Main(String[] args) in /Users/edwardnone/llama.cpp-dotnet/LlamaCppCli/Program.cs:line 112
   at LlamaCppCli.Program.<Main>(String[] args)
zsh: abort      ./LlamaCppCli 3 
```

It seems cant find the llama.cpp ? What did I do wrong ?

Thanks @dranger003

**Comment by x4080** [comment]
Never mind, I just copy file libllama.dylib to arm64/Release and all is working

Thanks for all your work, love it

**Comment by x4080** [comment]
BTW how to quit from CLI ? Tried Ctrl-C and not working 😄

**Comment by amirvenus** [comment]
> Never mind, I just copy file libllama.dylib to arm64/Release and all is working
> 
> Thanks for all your work, love it

Where can I find that file please?

**Comment by dranger003** [comment]
@amirvenus I don't use Apple Silicon but you should be able to get the file by [compiling llama.cpp](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#build) and [specifying BUILD_SHARED_LIBS](https://github.com/ggerganov/llama.cpp/blob/c50a82ce0f71558cbb8e555146ba124251504b38/CMakeLists.txt#L47) to generate the file.
